<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <url>https://github.com/celements/celements-RTE</url>
  <parent>
    <groupId>com.celements</groupId>
    <artifactId>celements-parent</artifactId>
    <version>7.2-SNAPSHOT</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <artifactId>celements-richtext-web</artifactId>
  <version>7.2-SNAPSHOT</version>
  <packaging>war</packaging>
  <name>Celements RichText web-module</name>
  <licenses>
    <license>
      <name>LGPL 2.1</name>
      <url>http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <dependencies>
    <!-- Add here all your dependencies -->
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-richtext</artifactId>
    </dependency>
  </dependencies>
  <build>
    <finalName>cel-richtext-web</finalName>
    <plugins>
      <plugin>
        <groupId>com.jarslab.maven</groupId>
        <artifactId>babel-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>js-transpile</id>
            <configuration>
              <babelSrc>${project.basedir}/babel-jslib/babel.min.js</babelSrc>
              <targetDir>${project.basedir}/target/${project.build.finalName}/resources/</targetDir>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <scm>
    <connection>scm:git:git://github.com/celements/celements-RTE</connection>
    <developerConnection>scm:git:git@github.com:celements/celements-RTE.git</developerConnection>
    <url>https://github.com/celements/celements-RTE/RichText-web-module</url>
    <tag>HEAD</tag>
  </scm>
</project>
